<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('prefix');
            $table->string('first_name');
            $table->string('last_name');
            $table->string('username')->unique();
            $table->string('password'); //AutoGenerated
            $table->date('dob');
            $table->string('gender');
            $table->string('email');
            $table->string('phone');
            $table->string('country');
            $table->string('branch');
            $table->string('photo')->nullable();
            $table->boolean('is_active')->default(false);
            $table->enum('approval_status', ['pending', 'accepted', 'declined']);
            $table->string('decline_reason')->nullable();
            $table->string('user_group');

            $table->bigInteger('creator_id')->unsigned();
            // $table->foreign('creator_id')->references('id')->on('users');
            $table->bigInteger('approver_id')->unsigned()->nullable();
            // $table->foreign('approver_id')->references('id')->on('users');
            
            $table->softDeletes();
            $table->timestamps();
        });

        $data = $this->getData();
        \DB::table('users')->insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }

    public function getData() {
        $data = [
            ['prefix'=> 'sys', 
            'first_name'=> 'System', 
            'last_name'=> 'Super User',
            'username'=> 'systemsuperuser', 
            'password'=> '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 
            'dob'=> date('Y-m-d'), 
            'gender'=> 'male', 
            'email'=> 'email@email.com', 
            'phone'=> '0000000000', 
            'country'=> 'ghana', 
            'branch'=> 'head-office', 
            'is_active'=> true, 
            'approval_status'=> 'accepted', 
            'user_group'=> 'system_user', 
            'creator_id'=> '1'],
        ];
        return $data;
    }
}
