<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('prefix');
            $table->string('first_name');
            $table->string('last_name');
            $table->string('username')->unique(); //AutoGenerated from fullname
            $table->string('password'); //AutoGenerated
            $table->date('dob');
            $table->string('gender');
            $table->string('email');
            $table->string('phone');
            $table->string('country');
            $table->string('branch');
            $table->string('photo')->nullable();
            $table->boolean('is_active')->default(false);

            $table->bigInteger('creator_id')->unsigned();
            // $table->foreign('creator_id')->references('id')->on('users');
            $table->bigInteger('approver_id')->unsigned()->nullable();
            // $table->foreign('approver_id')->references('id')->on('users');
            
            $table->softDeletes();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
